# Generated by Django 2.2.16 on 2022-08-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmation',
            name='username',
        ),
        migrations.AddField(
            model_name='confirmation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
