# Generated by Django 2.2.16 on 2022-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6ти значный код'),
        ),
    ]
