# Generated by Django 2.2.16 on 2022-08-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220824_0622'),
        ('users', '0002_user_confirmation_code'),
    ]

    operations: migrations.Migration = [
    ]
