# Generated by Django 2.2.16 on 2022-08-25 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220825_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmation', to=settings.AUTH_USER_MODEL),
        ),
    ]
