# Generated by Django 2.2.16 on 2022-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220828_1808'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('score__gt', 1), ('score__lt', 10)), name='check_score_range'),
        ),
    ]
