# Generated by Django 2.2.16 on 2022-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220828_1822'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='check_score_range',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 1), ('score__lte', 10)), name='check_score_range'),
        ),
    ]
