# Generated by Django 2.2.16 on 2022-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220828_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(verbose_name='оценка'),
        ),
    ]
